---

- name: add mozilla apt key
  ansible.builtin.apt_key:
    url: "{{ firefox_apt_key_url }}"
    keyring: "{{ firefox_apt_key_keyring }}"

- name: add mozilla repo
  ansible.builtin.apt_repository:
    repo: "{{ firefox_repo }}"
    state: present
    filename: mozilla

- name: prioritize packages from mozilla apt repo
  ansible.builtin.copy:
    src: etc/apt/preferences.d/mozilla.pref
    dest: /etc/apt/preferences.d/mozilla.pref
    owner: root
    group: root
    mode: 0644

- name: install latest mozilla firefox
  ansible.builtin.apt:
    name: firefox
    force_apt_get: true

...
